/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef rpc_TYPES_H
#define rpc_TYPES_H

#include <Thrift.h>
#include <TApplicationException.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>



namespace communication {

typedef struct _Point__isset {
  _Point__isset() : x(false), y(false), z(false) {}
  bool x;
  bool y;
  bool z;
} _Point__isset;

class Point {
 public:

  static const char* ascii_fingerprint; // = "EFFAD640FBA2CA56C50155B2A4545897";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xFA,0xD6,0x40,0xFB,0xA2,0xCA,0x56,0xC5,0x01,0x55,0xB2,0xA4,0x54,0x58,0x97};

  Point() : x(0), y(0), z(0) {
  }

  virtual ~Point() throw() {}

  double x;
  double y;
  double z;

  _Point__isset __isset;

  void __set_x(const double val) {
    x = val;
  }

  void __set_y(const double val) {
    y = val;
  }

  void __set_z(const double val) {
    z = val;
  }

  bool operator == (const Point & rhs) const
  {
    if (!(x == rhs.x))
      return false;
    if (!(y == rhs.y))
      return false;
    if (!(z == rhs.z))
      return false;
    return true;
  }
  bool operator != (const Point &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Point & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Color__isset {
  _Color__isset() : r(false), g(false), b(false) {}
  bool r;
  bool g;
  bool b;
} _Color__isset;

class Color {
 public:

  static const char* ascii_fingerprint; // = "6435B39C87AB0E30F30BEDEFD7328C0D";
  static const uint8_t binary_fingerprint[16]; // = {0x64,0x35,0xB3,0x9C,0x87,0xAB,0x0E,0x30,0xF3,0x0B,0xED,0xEF,0xD7,0x32,0x8C,0x0D};

  Color() : r(0), g(0), b(0) {
  }

  virtual ~Color() throw() {}

  int32_t r;
  int32_t g;
  int32_t b;

  _Color__isset __isset;

  void __set_r(const int32_t val) {
    r = val;
  }

  void __set_g(const int32_t val) {
    g = val;
  }

  void __set_b(const int32_t val) {
    b = val;
  }

  bool operator == (const Color & rhs) const
  {
    if (!(r == rhs.r))
      return false;
    if (!(g == rhs.g))
      return false;
    if (!(b == rhs.b))
      return false;
    return true;
  }
  bool operator != (const Color &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Color & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PointCloud__isset {
  _PointCloud__isset() : points(false), average(false), identifier(false), color(false) {}
  bool points;
  bool average;
  bool identifier;
  bool color;
} _PointCloud__isset;

class PointCloud {
 public:

  static const char* ascii_fingerprint; // = "77062B174AF362E04E6A39C156B455CF";
  static const uint8_t binary_fingerprint[16]; // = {0x77,0x06,0x2B,0x17,0x4A,0xF3,0x62,0xE0,0x4E,0x6A,0x39,0xC1,0x56,0xB4,0x55,0xCF};

  PointCloud() : identifier("") {
  }

  virtual ~PointCloud() throw() {}

  std::vector<Point>  points;
  Point average;
  std::string identifier;
  Color color;

  _PointCloud__isset __isset;

  void __set_points(const std::vector<Point> & val) {
    points = val;
  }

  void __set_average(const Point& val) {
    average = val;
  }

  void __set_identifier(const std::string& val) {
    identifier = val;
  }

  void __set_color(const Color& val) {
    color = val;
  }

  bool operator == (const PointCloud & rhs) const
  {
    if (!(points == rhs.points))
      return false;
    if (!(average == rhs.average))
      return false;
    if (!(identifier == rhs.identifier))
      return false;
    if (!(color == rhs.color))
      return false;
    return true;
  }
  bool operator != (const PointCloud &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PointCloud & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

} // namespace

#endif
