/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "rpc_constants.h"

namespace communication {

const rpcConstants g_rpc_constants;

rpcConstants::rpcConstants() {
}

} // namespace

